ALTER TABLE assinantes
ADD COLUMN IF NOT EXISTS billing_nome VARCHAR(150),
ADD COLUMN IF NOT EXISTS billing_cpf_cnpj VARCHAR(20),
ADD COLUMN IF NOT EXISTS billing_email VARCHAR(150),
ADD COLUMN IF NOT EXISTS billing_telefone VARCHAR(30);
